name: clean data
on: 
  workflow_dispatch:
  schedule:
  - cron: 0 2 * * *

env:
  TZ: Asia/Shanghai
  SMARTDNS_URL: https://github.com/pymumu/smartdns/releases/download/Release45/smartdns-x86_64
  SMARTDNS_PATH: /tmp/smartdns

jobs:
  Generate_Blacklist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Setup Python 3.9.x
        uses: actions/setup-python@main
        with:
          python-version: '3.9.x'

      - name: clean data
        id: update
        run: |
          python clean-readme.py
          rm -rf __pycache__
          echo "message=$(date)" >> $GITHUB_OUTPUT
          
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ${{ steps.update.outputs.message }}
          
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 5
