name: Update ReadMe
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'
    
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
          
      - name: Update Title&ReadMe
        run: |

          python clean-readme.py

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ${{ steps.update.outputs.message }}
          
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 5
